JC	= javac
JFLAGS	= -Xlint 

all: \
	Couleur.class	\
	RougeNoir.class	\
	Etudiant.class	\
	NoeudRN.class	\
	ProgrammeGestion.class \
	Main.class	

	mv -f *.class ../class

Couleur.class:			Couleur.java
				$(JC) $(JFLAGS) Couleur.java

RougeNoir.class:		RougeNoir.java
				$(JC) $(JFLAGS) RougeNoir.java

Etudiant.class:			Etudiant.java
				$(JC) $(JFLAGS) Etudiant.java

NoeudRN.class:			NoeudRN.java
				$(JC) $(JFLAGS) NoeudRN.java

ProgrammeGestion.class:		ProgrammeGestion.java
				$(JC) $(JFLAGS) ProgrammeGestion.java

Main.class:			Main.java
				$(JC) $(JFLAGS) Main.java



